# Generated by Django 5.1.4 on 2025-01-06 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('firstname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, underscores, and dots are allowed.', regex='^[A-Za-z0-9_\\.]+$')], verbose_name='First Name')),
                ('lastname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, underscores, and dots are allowed.', regex='^[A-Za-z0-9_\\.]+$')], verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('service', models.CharField(choices=[('frntend', 'Frontend Development'), ('bckend', 'Backend Development'), ('iot', 'Web Server/IOT'), ('embedded', 'Embedded System Design'), ('other', 'Other')], max_length=10)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
