# Generated by Django 5.1.4 on 2025-01-07 08:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_sender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedemail',
            name='message',
            field=models.TextField(verbose_name=django.core.validators.MinLengthValidator(10, message='Message must be at least 10 characters')),
        ),
    ]
